let events=[],filter='all';const $=s=>document.querySelector(s);const esc=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const SOURCES=[['FDA','美国监管 / 肿瘤批准','https://www.fda.gov/drugs/resources-information-approved-drugs/oncology-cancer-hematologic-malignancies-approval-notifications'],['EMA','欧盟监管','https://www.ema.europa.eu/en/news-events'],['NMPA','中国药监','https://www.nmpa.gov.cn/'],['CDE','中国药审中心','https://www.cde.org.cn/'],['ClinicalTrials.gov','全球临床试验','https://clinicaltrials.gov/'],['中国药物临床试验登记平台','中国临床试验','http://www.chinadrugtrials.org.cn/'],['ASCO','肿瘤临床','https://www.asco.org/'],['AACR','肿瘤研究','https://www.aacr.org/'],['ESMO','欧洲肿瘤临床','https://www.esmo.org/'],['PubMed','医学论文','https://pubmed.ncbi.nlm.nih.gov/'],['Fierce Biotech','Biotech / 管线 / BD','https://www.fiercebiotech.com/'],['Fierce Pharma','Pharma / BD','https://www.fiercepharma.com/'],['BioSpace','融资 / Biotech','https://www.biospace.com/'],['SEC EDGAR','美股公告','https://www.sec.gov/edgar/search/'],['港交所披露易','港股公告','https://www.hkexnews.hk/'],['上交所','A股公告','https://www.sse.com.cn/']];
const LEARN=[['肿瘤药物','ADC 是什么？','抗体识别肿瘤抗原，linker 连接细胞毒载荷。看 ADC 时关注靶点、DAR、旁观者效应、安全窗和耐药。'],['临床指标','ORR、PFS、OS 怎么读？','ORR 看缩瘤比例，PFS 看疾病不进展时间，OS 看总生存。跨癌种、线次和研究设计不能机械横比。'],['研发阶段','Phase I / II / III 意味着什么？','I 期看安全和剂量，II 期寻找疗效信号与 PoC，III 期确证获益；越后期单项目临床成本通常越高。'],['肿瘤机制','PD-1 / VEGF 双抗为何热门？','同时解除免疫抑制并影响肿瘤血管微环境。阅读数据时要同时看疗效、安全性、患者分层和对照方案。'],['靶向治疗','KRAS、EGFR、HER2 怎么理解？','靶点决定生物学机制，mutation、expression、amplification 等 biomarker 决定患者人群与竞争边界。'],['新技术','双抗 / TCE 是什么？','双抗同时结合两个靶点；TCE 常把 T 细胞与肿瘤细胞拉近。重点关注 CRS、神经毒性和给药便利性。'],['BD','License-out 交易怎么看？','拆开 headline value：upfront、开发/注册里程碑、销售里程碑、royalty、地区权益与共同开发成本。'],['财务','研发新闻如何影响 Forecast？','项目提速会改变 CRO、中心费、药物供应、检测、FTE 和里程碑付款的时间。Finance BP 要盯 phasing。'],['融资','Biotech 融资为什么关键？','关注 cash runway、季度 burn、融资工具与稀释，以及现有现金能否覆盖到下一个关键数据节点。']];
function norm(x){if(x.sources)return x;return {...x,region:x.region||'Global',tags:x.tags||[],sources:[{name:x.source||'Source',url:x.url||'#'}],why:x.why||''}}
function match(e,q){return [e.title,e.summary,e.category,e.region,(e.tags||[]).join(' '),...(e.sources||[]).map(x=>x.name)].join(' ').toLowerCase().includes(q)}
function render(){const q=$('#search').value.trim().toLowerCase();const rows=events.filter(e=>(filter==='all'||e.category===filter||(e.tags||[]).includes(filter))&&(!q||match(e,q)));$('#stories').innerHTML=rows.length?rows.map(e=>`<article class="event"><div class="eventtop"><div><div class="eventmeta"><span class="badge">${esc(e.category)}</span>${(e.tags||[]).includes('Oncology')?'<span class="badge oncology">肿瘤</span>':''}${e.region==='China'?'<span class="badge cn">中国</span>':''}<span class="badge">${e.sources.length} 个来源</span></div><h3>${esc(e.title)}</h3></div><span class="score">${e.score}</span></div><p>${esc(e.summary)}</p>${e.why?`<p class="why"><b>BP 关注：</b>${esc(e.why)}</p>`:''}<div class="eventfoot"><div class="sourceLinks">${e.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)} ↗</a>`).join('')}</div><time>${esc(e.date)}</time></div></article>`).join(''):'<div class="empty">没有匹配内容</div>';$('#rank').innerHTML=events.slice().sort((a,b)=>b.score-a.score).slice(0,10).map((e,i)=>`<div class="rankitem"><span class="ranknum">${String(i+1).padStart(2,'0')}</span><span class="ranktitle">${esc(e.title)}</span><span class="rankscore">${e.score}</span></div>`).join('')}
function setFilter(v){filter=v;document.querySelectorAll('.topic').forEach(x=>x.classList.toggle('active',x.dataset.filter===v));$('#newsView').classList.remove('hidden');$('#learnView').classList.add('hidden');render()}
async function load(){try{const r=await fetch('data/news.json?'+Date.now());const d=await r.json();events=(d.items||[]).map(norm);$('#updatedAt').textContent=d.updated_at||'—';$('#stats').textContent=`${events.length} 个事件 · ${new Set(events.flatMap(e=>e.sources.map(s=>s.name))).size} 个来源`;render()}catch(e){$('#stories').innerHTML='<div class="empty">数据加载失败，请刷新页面</div>'}}
function setup(){document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>setFilter(b.dataset.filter)));document.querySelectorAll('[data-view="learn"]').forEach(b=>b.addEventListener('click',()=>{$('#newsView').classList.add('hidden');$('#learnView').classList.remove('hidden')}));$('#search').addEventListener('input',render);$('#learnGrid').innerHTML=LEARN.map(x=>`<div class="learncard"><span class="k">${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('');$('#sourceGrid').innerHTML=SOURCES.map(x=>`<a class="sourceitem" href="${x[2]}" target="_blank"><b>${x[0]}</b><span>${x[1]}</span><i>打开来源 ↗</i></a>`).join('');$('#sourceMini').innerHTML=SOURCES.slice(0,8).map(x=>`<a href="${x[2]}" target="_blank">${x[0]} · ${x[1]} ↗</a>`).join('')}
setup();load();