let events=[],filter='all';
const $=s=>document.querySelector(s),esc=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const KEY='pharmahot_glossary_favorites';
const GLOSSARY={
'PD-L1':['肿瘤或免疫细胞表面的免疫检查点配体，可与T细胞PD-1结合并抑制免疫反应。','关注患者筛选、单药/联合及不同表达亚组疗效。','影响可治疗人群、伴随诊断成本和商业峰值。'],
'PD-1':['T细胞表面的免疫检查点受体。','关注联合方案、治疗线次、ORR/PFS/OS。','成熟靶点竞争激烈，差异化决定商业空间。'],
'ADC':['抗体偶联药物，用抗体把细胞毒载荷递送至肿瘤。','重点看靶点、linker、payload、DAR、旁观者效应和安全窗。','CMC、payload供应和CDMO复杂度通常更高。'],
'CAR-T':['工程化T细胞治疗。','看靶点、缓解持续时间、CRS及自体/异体。','生产、冷链、中心认证和按单制造决定特殊成本结构。'],
'ORR':['客观缓解率。','必须与DoR、PFS、样本量和线次一起看。','早期信号可能触发扩展和预算追加。'],
'DoR':['缓解持续时间。','与ORR一起判断疗效是否持久。','持续性影响注册开发价值。'],
'PFS':['无进展生存期。','看HR、中位PFS、置信区间和对照。','关键终点可能触发注册与商业投入。'],
'OS':['总生存期。','成熟需要较长随访。','等待OS会拉长临床周期和现金消耗。'],
'PoC':['概念验证。','是项目重要价值跃升点。','会改变预算、BD估值和资源优先级。'],
'BLA':['生物制品上市许可申请。','受理后进入监管审评和上市准备。','商业批、供应和商业团队投入前移。'],
'IND':['新药临床试验申请。','关注获准后首例入组时间。','支出从研究/CMC逐步转向临床运营。'],
'upfront':['BD签约首付款。','与总交易额和里程碑分开看。','最接近短期现金流。'],
'milestone':['或有里程碑付款。','不能把headline value全部当确定收入。','建模要考虑概率和时间。']};
const TERM_RE=/PD-L1|PD-1|CAR-T|upfront|milestone|ADC|ORR|DoR|PFS|OS|PoC|BLA|IND/g;
const COMPANY_UPDATES=[
{company:'复宏汉霖',date:'2026-07-31',type:'临床/管线',title:'PD-L1 ADC HLX43新增联合治疗临床批准',summary:'HLX43联合贝伐珠单抗并联合/不联合化疗用于晚期/转移性实体瘤的临床研究获NMPA批准；HLX43已覆盖多类实体瘤并累计入组逾1000例。',bp:'从单药走向组合疗法，会提高中心、药品供应、检测和组合用药管理复杂度；若进入更前线治疗，患者规模和临床预算都会放大。',url:'https://www.henlius.com/NewsDetails-6066-26.html'},
{company:'复宏汉霖',date:'2026-07-30',type:'FIH',title:'三抗TCE HLX3902完成全球首例患者给药',summary:'STEAP1×CD3×CD28三特异性TCE进入I期，面向转移性去势抵抗性前列腺癌及其他晚期实体瘤，中国和澳大利亚同步推进。',bp:'FIH是“平台→临床验证”的关键节点，短期支出从CMC/毒理转向临床运营；真正价值拐点仍要等安全性、剂量和早期疗效。',url:'https://www.henlius.com/NewsDetails-6062-26.html'},
{company:'恒瑞医药',date:'2026-05-19',type:'Phase III',title:'HER3 ADC SHR-A2009 III期达到主要终点',summary:'EGFR TKI治疗失败的EGFR突变晚期NSCLC研究中，SHR-A2009对比含铂双药化疗显著延长PFS；公司计划与CDE开展上市前沟通。',bp:'III期成功后支出重心会从临床执行转向注册、商业批、医学事务和上市准备；同靶点竞品的估值和优先级也会被重新评估。',url:'https://www.hengrui.com/media/detail-953.html'},
{company:'恒瑞医药',date:'2026-05-12',type:'BD',title:'与BMS达成13项目全球战略合作，潜在总额约152亿美元',summary:'合作含4项恒瑞肿瘤/血液资产、4项BMS免疫项目及5项共同发现项目；恒瑞可获6亿美元首付款及后续近期付款和里程碑。',bp:'这是portfolio deal，不应只看152亿美元headline value；Finance要拆upfront、近期固定付款、研发成本分担、选择权和概率加权里程碑。',url:'https://www.hengrui.com/media/detail-950.html'},
{company:'恒瑞医药',date:'2026-04-23',type:'财报',title:'一季度创新药销售45.26亿元，研发投入22.24亿元',summary:'Q1营收81.41亿元，同比增长12.98%；创新药销售占药品销售收入61.69%，抗肿瘤创新药收入33.13亿元。',bp:'可用于做“研发强度→创新药收入兑现”的同行benchmark；同时要区分研发费用化和资本化口径及BD收入对利润的影响。',url:'https://www.hengrui.com/media/detail-941.html'},
{company:'信达生物',date:'2026-06-01',type:'临床',title:'IBI363在免疫耐药NSCLC显示长期生存信号并进入全球III期',summary:'IBI363单药长期随访显示免疫耐药鳞状/非鳞NSCLC生存获益；鳞状NSCLC全球III期MarsLight-11已启动。',bp:'从PoC到全球III期意味着单项目现金消耗和跨区域临床运营复杂度显著上升；也是BD价值进一步兑现的阶段。',url:'https://en.innoventbio.com/InvestorsAndMedia/PressReleaseDetail?key=600'},
{company:'信达生物',date:'2026-03-26',type:'财报/战略',title:'2025收入突破100亿元，进入盈利与全球化阶段',summary:'公司披露年度业绩并强调“肿瘤+综合生物医药”双引擎，管线从中国商业化向全球开发扩张。',bp:'财务上要关注销售增长能否覆盖全球研发投入、海外III期和商业化前置成本；利润拐点不等于现金投入下降。',url:'https://en.innoventbio.com/InvestorsAndMedia/PressReleaseDetail?key=584'},
{company:'再鼎医药',date:'2026-06-16',type:'监管',title:'DLL3 ADC zoci获EMA孤儿药资格',summary:'zocilurtatug pelitecan用于肺部神经内分泌癌获EMA孤儿药资格，此前已获FDA相关资格并公布SCLC/NEC早期数据。',bp:'孤儿药资格本身不是获批，但可优化注册互动与市场策略；真正预算拐点仍在注册性研究启动和患者入组规模扩大。',url:'https://ir.zailaboratory.com/news-releases/news-release-details/zai-lab-receives-ema-orphan-drug-designation-zocilurtatug'},
{company:'再鼎医药',date:'2026-06-08',type:'获批/商业化',title:'TIVDAK获NMPA批准用于复发或转移性宫颈癌',summary:'中国批准基于全球III期innovaTV 301，研究显示OS获益；产品由再鼎在中国推进商业化。',bp:'获批后重点从研发费用转向库存、渠道、医学教育、市场准入和销售爬坡；应关注上市初期销售效率与推广投入。',url:'https://ir.zailaboratory.com/zh-hans/news-releases/news-release-details-94'},
{company:'再鼎医药',date:'2026-05-07',type:'财报',title:'Q1收入9960万美元，zoci注册性开发继续提速',summary:'Q1产品收入受则乐竞争和医保价格调整影响；zoci在SCLC和epNEC数据推动后计划继续注册性开发，并有多项商业化新品准备。',bp:'非常典型的“存量产品承压+新产品投入”组合；Finance要关注销售下滑、launch investment和全球管线现金消耗的错配。',url:'https://ir.zailaboratory.com/zh-hans/news-releases/news-release-details/zaidingyiyaogongbu-2026niandiyijiducaiwuyejihejinqigongsijinzhan?mobile=1'},
{company:'和黄医药',date:'2026-06-12',type:'Phase III',title:'Sovleplenib III期ESLIM-02数据亮相EHA',summary:'wAIHA患者中显示快速且持久的血红蛋白应答，NDA已在中国获受理并进入优先审评。',bp:'III期数据+优先审评意味着商业化准备可能明显前移；同时需评估非肿瘤产品对公司收入结构和销售团队配置的改变。',url:'https://www.hutch-med.com/eslim-02-eha26/'},
{company:'和黄医药',date:'2026-05-21',type:'获批/商业化',title:'呋喹替尼联合信迪利单抗获批用于晚期肾癌',summary:'NMPA批准ELUNATE+TYVYT用于既往VEGFR-TKI治疗失败的局晚/转移性肾癌；FRUSICA-2中疾病进展或死亡风险下降63%。',bp:'联合用药获批会改变单药商业模型，需关注分成、渠道协同、医保和组合用药渗透率。',url:'https://www.hutch-med.com/nmpa-approval-for-elunate-fruquintinib-plus-tyvyt-sintilimab-for-rcc/'},
{company:'和黄医药',date:'2026-03-05',type:'财报/商业化',title:'2025全年FRUZAQLA海外销售增长26%，核心业务盈利改善',summary:'Takeda负责的FRUZAQLA海外市场销售增长至3.662亿美元；公司年末现金约14亿美元，同时继续推进ATTC等新平台。',bp:'这是“授权商业化+里程碑+自营产品”混合模式案例，收入质量要拆分产品销售、royalty/分成、里程碑和一次性处置收益。',url:'https://www.hutch-med.com/2025-full-year-results/'}];
const LEARN=[
{tag:'研发阶段',title:'从FIH到III期：为什么预算曲线会越来越陡？',body:'FIH核心是安全、剂量和PK；PoC开始回答“在人身上是否有效”；III期则要用更大样本确证获益。',case:'案例对比：复宏汉霖HLX3902刚完成全球首例给药，预算集中在早期中心、剂量递增和CMC；恒瑞SHR-A2009已III期达到主要终点，下一步更多是注册、商业批和上市准备。',bp:'BP问题：未来12个月哪几个资产会从“探索性预算”切换成“大规模开发预算”？这种阶段切换比单纯看年度总额更重要。'},
{tag:'ADC',title:'同样是ADC，为什么价值差异可以非常大？',body:'ADC不是一个单一类别，靶点、payload、linker、DAR、旁观者效应、安全窗和适应症都决定临床价值。',case:'案例对比：恒瑞HER3 ADC SHR-A2009已走到III期主要终点；再鼎TIVDAK已在中国获批；复宏汉霖HLX43仍在拓展联合治疗。三个资产处在完全不同的风险/现金流阶段。',bp:'BP问题：不要只问“是不是ADC”，要问“离注册还有多远、制造复杂度多高、需要多少商业化准备、同靶点竞争是否拥挤”。'},
{tag:'BD',title:'152亿美元交易，不等于152亿美元收入',body:'BD headline value通常由upfront、近期固定付款、开发/注册/销售里程碑和royalty组成。',case:'恒瑞-BMS 13项目合作潜在总额约152亿美元，但较确定的是6亿美元首付款及部分近期付款；后续大量金额取决于选择权和项目成功。',bp:'BP问题：做预算或估值时至少分成“确定现金”“概率加权现金”“远期销售提成”三层，否则很容易高估短期财务影响。'},
{tag:'临床数据',title:'ORR很高，为什么还不能马上判定项目成功？',body:'ORR是缩瘤比例，DoR看持续多久，PFS看不进展时间，OS看最终生存；样本量、治疗线次和对照设计同样关键。',case:'例如早期PoC可能出现非常亮眼ORR，但如果样本少、随访短或缺乏随机对照，价值仍低于随机III期的PFS/OS阳性结果。',bp:'BP问题：预算追加要和“证据强度”挂钩，而不是和单个漂亮数字挂钩。'},
{tag:'商业化',title:'获批之后，钱为什么反而花得更多？',body:'获批前后支出结构会从临床研发转向库存、商业批、医学事务、市场准入、销售团队和患者教育。',case:'再鼎TIVDAK从III期到NMPA获批，就是从“研发资产”切换成“商业化产品”；和黄呋喹替尼联合信迪利单抗获批后，还涉及组合用药、伙伴协同和市场准入。',bp:'BP问题：launch year要把销量爬坡和费用前置放在一起看，短期利润率可能先承压。'},
{tag:'财报',title:'研发强度高，到底是好事还是坏事？',body:'关键不是研发费用绝对值，而是研发投入是否对应高质量资产、明确里程碑和未来收入。',case:'恒瑞Q1研发投入22.24亿元、创新药销售45.26亿元；信达则已进入年收入百亿元和全球III期扩张阶段。两家公司研发效率不能只用“研发费用率”单指标比较。',bp:'BP问题：最好同时看研发费用率、临床后期资产数量、未来24个月关键读出、BD现金流和创新药收入增长。'},
{tag:'商业模式',title:'自营、授权、联合开发：哪种模式更赚钱？',body:'自营保留更多长期利润但需要更大销售和开发投入；授权降低现金消耗但让渡权益；联合开发介于两者之间。',case:'和黄FRUZAQLA海外由Takeda商业化，体现“伙伴放大海外销售”；恒瑞-BMS则更接近多资产联合开发；再鼎同时拥有引进产品商业化和自研全球管线。',bp:'BP问题：比较的不是毛利率，而是风险调整后的资本回报和现金流时间。'}];
function rich(s){return esc(s).replace(TERM_RE,t=>`<button class="term" data-term="${t}">${t}<sup>?</sup></button>`)}
function favs(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){return[]}}
function renderFavs(){let a=favs();$('#favCount').textContent=a.length;$('#favTermsMini').innerHTML=a.length?a.map(k=>`<button class="favterm" data-fav="${k}">★ ${k}</button>`).join(''):'<div class="favempty">点击正文中的术语即可收藏</div>';document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>showTerm(b.dataset.fav))}
function showTerm(k){let x=GLOSSARY[k];if(!x)return;$('#termPopover')?.remove();let on=favs().includes(k),d=document.createElement('div');d.id='termPopover';d.className='termPopover';d.innerHTML=`<button class="termClose">×</button><small>术语科普</small><h3>${k}</h3><p><b>是什么：</b>${x[0]}</p><p><b>新闻怎么看：</b>${x[1]}</p><p><b>Finance BP：</b>${x[2]}</p><button class="termFav">${on?'★ 已收藏':'☆ 收藏术语'}</button>`;document.body.appendChild(d);d.querySelector('.termClose').onclick=()=>d.remove();d.querySelector('.termFav').onclick=()=>{let a=favs();a=a.includes(k)?a.filter(v=>v!==k):[...a,k];localStorage.setItem(KEY,JSON.stringify(a));renderFavs();showTerm(k)}}
function bindTerms(){document.querySelectorAll('.term').forEach(b=>b.onclick=()=>showTerm(b.dataset.term))}
function eventId(e){let h=0;for(const c of e.title){h=((h<<5)-h)+c.charCodeAt(0);h|=0}return'e'+Math.abs(h)}
function match(e,q){return[e.title,e.summary,e.category,e.region,...(e.tags||[])].join(' ').toLowerCase().includes(q.toLowerCase())}
function jump(id){filter='all';render();requestAnimationFrame(()=>{let el=document.getElementById(id);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('rank-highlight');setTimeout(()=>el.classList.remove('rank-highlight'),2000)}})}
function render(){let q=$('#search').value.trim(),rows=events.filter(e=>(filter==='all'||e.category===filter||(e.tags||[]).includes(filter))&&(!q||match(e,q)));$('#stories').innerHTML=rows.length?rows.map(e=>`<article class="event" id="${eventId(e)}"><div class="eventtop"><div><div class="eventmeta"><span class="badge">${esc(e.category)}</span>${(e.tags||[]).includes('Oncology')?'<span class="badge strong">肿瘤</span>':''}<span class="badge">${e.sources.length}来源</span></div><h3>${rich(e.title)}</h3></div><span class="score">● ${e.score}</span></div><p>${rich(e.summary)}</p>${e.why?`<p class="why"><b>BP关注：</b>${rich(e.why)}</p>`:''}<div class="eventfoot"><div class="sourceLinks">${e.sources.map(s=>`<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)} ↗</a>`).join('')}</div><time>${e.date}</time></div></article>`).join(''):'<div class="empty">没有匹配内容</div>';let top=events.slice().sort((a,b)=>b.score-a.score).slice(0,10);$('#rankList').innerHTML=top.map((e,i)=>`<button class="rankitem" data-jump="${eventId(e)}"><span class="ranknum">${String(i+1).padStart(2,'0')}</span><span class="ranktitle">${esc(e.title)}</span><span class="rankscore">${e.score}</span></button>`).join('');$('#keyUpdates').innerHTML=top.slice(0,4).map((e,i)=>`<button class="hotrow" data-jump="${eventId(e)}"><span class="hotnum">${i+1}</span><span class="hottitle">${esc(e.title)}</span><span class="hotscore">${e.score} 热度</span></button>`).join('');document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>jump(b.dataset.jump));bindTerms()}
function renderCompanies(){$('#companyGrid').innerHTML=COMPANY_UPDATES.map(x=>`<article class="companyupdate"><div class="companyline"><span class="companyname">${x.company}</span><span class="companytype">${x.type}</span><time>${x.date}</time></div><h3>${rich(x.title)}</h3><p>${rich(x.summary)}</p><p class="companybp"><b>BP看点：</b>${rich(x.bp)}</p><a href="${x.url}" target="_blank" rel="noopener">查看具体公告/新闻 ↗</a></article>`).join('');bindTerms()}
function renderLearn(){$('#learnGrid').innerHTML=LEARN.map(x=>`<article class="learncard deep"><span class="k">${x.tag}</span><h3>${x.title}</h3><p>${x.body}</p><div class="case"><b>企业案例</b><p>${x.case}</p></div><div class="bptake"><b>Finance BP怎么用</b><p>${x.bp}</p></div></article>`).join('')}
function wire(){document.querySelectorAll('.topic').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('.topic').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelectorAll('.sideitem[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();$('#news').scrollIntoView({behavior:'smooth'})});document.querySelectorAll('[data-scrollto]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scrollto)?.scrollIntoView({behavior:'smooth'}));$('#search').oninput=render;$('#searchBtn').onclick=render;$('#favTermsBtn').onclick=()=>$('#rank').scrollIntoView({behavior:'smooth'});document.querySelector('[data-view="learn"]').onclick=()=>{$('#learnView').classList.remove('hidden');$('#learnView').scrollIntoView({behavior:'smooth'})}}
async function boot(){renderCompanies();renderLearn();renderFavs();wire();try{let r=await fetch('./data/news.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);let d=await r.json();events=(d.items||[]).map(x=>({...x,region:x.region||'Global',tags:x.tags||[],sources:x.sources||[{name:x.source||'来源',url:x.url||'#'}],why:x.why||''}));$('#updatedAt').textContent=d.updated_at||'最新';render()}catch(e){console.error(e);$('#stories').innerHTML='<div class="empty">新闻数据加载失败，请刷新页面重试。</div>';$('#keyUpdates').innerHTML='<div class="empty">重点进展暂时加载失败</div>'}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();